project:
  type: website
  output-dir: docs

# Can customize this section with options from the following page:
# https://quarto.org/docs/websites/website-navigation.html
website:
  title: "Formula 1 Blog Project"
  # Preview image to be included in course landing page for all blogs.
  # Specify your own filepath or URL.
  image: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExaXJkZ2g2cTYxa2prazNxdGZyNnZoNjBrOXJzN2x1czk1OXI5eWRqZSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/vijrOPnOo9RVC/giphy.gif"
  navbar:
    left:
      - href: index.qmd # Must be included as index.qmd
        text: "Home"
        icon: speedometer # Get icon names: https://icons.getbootstrap.com/?q=home
      # Add or remove additional pages below in desired order of appearance
      - href: another-page.qmd
        text: "Network Page"
        icon: car-front
      - href: yet-another-page.qmd
        text: "Yet another page with a custom label and icon"
        icon: arrow-through-heart-fill
        
format:
  html:
    date: last-modified
    published-title: "Last updated"
    date-format: "MMMM D, YYYY"
    toc: true
    toc-expand: true
    crossrefs-hover: false
    code-line-numbers: true
    bibliography: "bib/library.bib" # Edit the contents of this file
    csl: "bib/american-statistical-association.csl"
    nocite: "@*"
    # Update any of the following options to modify the theme
    # See https://quarto.org/docs/output-formats/html-code.html#highlighting
    highlight-style: arrow
    # See https://quarto.org/docs/output-formats/html-themes.html
    theme: 
      light: [journal, theme-light.scss]
      dark: vapor
    fontsize: 13pt
    # If you want to customize beyond a built-in theme, you can add content to
    # styles.css (currently empty). See the following page for more info:
    # https://quarto.org/docs/output-formats/html-themes.html#custom-themes
    css: styles.css 

# Add default code chunk execution options here
execute:
  echo: false

  