---
title: "Network Page"
author: "Sam Ramirez"
---

This is just another page that can be linked! You are not required to include more than just *index.qmd*, but you are welcome to make content on different pages, if desired. This may help with managing GitHub commits, as well.

```{r}
#| label: setup
#| include: false

# Improve digit display and NA display for kable tables
options(scipen = 1, knitr.kable.NA = "")

# Load necessary packages
library(tidyverse)
library(knitr)
library(kableExtra)
library(igraph)
library(tidygraph)
library(ggraph)
library(ggnetwork)
```



```{r}
#| label: nodes and edges #IMCOMPLETE!!!!!!!

load("network_data.RData")

network_graph <- as_tbl_graph(prix_by_id, directed = TRUE)

glimpse(network_graph)

# Isolate nodes and edges ===============

# Create tibble of edges
network_edges <- with_graph(network_graph, .E()) 

# Create tibble of nodes
network_nodes <- with_graph(network_graph, .N()) 



# my_countries <- 
#   c("Argentina", "Brazil", "Italy")
# 
# prix_graph <-
#   prix_by_id |> 
#   activate(nodes) |>
#   # Modify code with the name of your sample
#   filter(name %in% my_countries)
# 
# ggraph(prix_graph10) + 
#   geom_edge_link() +
#   geom_node_point() +
#   geom_node_label(aes(label = name)) +
#   # Had to add `base_family` argument due to error with fonts loading for PDF
#   theme_graph(base_family = "sans") 


```

